// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kvaft-rpc.proto

package io.zealab.kvaft.rpc.protoc;

public final class RemoteCalls {
    private RemoteCalls() {}

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface HeartbeatOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.zealab.kvaft.rpc.protoc.Heartbeat)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 timestamp = 1;</code>
         */
        long getTimestamp();
    }

    /**
     * Protobuf type {@code io.zealab.kvaft.rpc.protoc.Heartbeat}
     */
    public static final class Heartbeat extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.zealab.kvaft.rpc.protoc.Heartbeat)
            HeartbeatOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Heartbeat.newBuilder() to construct.
        private Heartbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Heartbeat() {
            timestamp_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Heartbeat(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            timestamp_ = input.readInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat.class, io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat.Builder.class);
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 1;
        private long timestamp_;

        /**
         * <code>int64 timestamp = 1;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (timestamp_ != 0L) {
                output.writeInt64(1, timestamp_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, timestamp_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat)) {
                return super.equals(obj);
            }
            io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat other = (io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat) obj;

            boolean result = true;
            result = result && (getTimestamp()
                    == other.getTimestamp());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.zealab.kvaft.rpc.protoc.Heartbeat}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.zealab.kvaft.rpc.protoc.Heartbeat)
                io.zealab.kvaft.rpc.protoc.RemoteCalls.HeartbeatOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat.class, io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat.Builder.class);
            }

            // Construct using io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                timestamp_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_descriptor;
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat getDefaultInstanceForType() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat.getDefaultInstance();
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat build() {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat buildPartial() {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat result = new io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat(this);
                result.timestamp_ = timestamp_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat) {
                    return mergeFrom((io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat other) {
                if (other == io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat.getDefaultInstance()) {
                    return this;
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long timestamp_;

            /**
             * <code>int64 timestamp = 1;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>int64 timestamp = 1;</code>
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 timestamp = 1;</code>
             */
            public Builder clearTimestamp() {

                timestamp_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:io.zealab.kvaft.rpc.protoc.Heartbeat)
        }

        // @@protoc_insertion_point(class_scope:io.zealab.kvaft.rpc.protoc.Heartbeat)
        private static final io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat();
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Heartbeat>
                PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
            @java.lang.Override
            public Heartbeat parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Heartbeat(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Heartbeat> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Heartbeat> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.zealab.kvaft.rpc.protoc.RemoteCalls.Heartbeat getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface PreVoteReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.zealab.kvaft.rpc.protoc.PreVoteReq)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string server_id = 1;</code>
         */
        java.lang.String getServerId();

        /**
         * <code>string server_id = 1;</code>
         */
        com.google.protobuf.ByteString
        getServerIdBytes();

        /**
         * <code>string peer_id = 2;</code>
         */
        java.lang.String getPeerId();

        /**
         * <code>string peer_id = 2;</code>
         */
        com.google.protobuf.ByteString
        getPeerIdBytes();

        /**
         * <code>uint64 term = 3;</code>
         */
        long getTerm();
    }

    /**
     * Protobuf type {@code io.zealab.kvaft.rpc.protoc.PreVoteReq}
     */
    public static final class PreVoteReq extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.zealab.kvaft.rpc.protoc.PreVoteReq)
            PreVoteReqOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use PreVoteReq.newBuilder() to construct.
        private PreVoteReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PreVoteReq() {
            serverId_ = "";
            peerId_ = "";
            term_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private PreVoteReq(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            serverId_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            peerId_ = s;
                            break;
                        }
                        case 24: {

                            term_ = input.readUInt64();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq.class, io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq.Builder.class);
        }

        public static final int SERVER_ID_FIELD_NUMBER = 1;
        private volatile java.lang.Object serverId_;

        /**
         * <code>string server_id = 1;</code>
         */
        public java.lang.String getServerId() {
            java.lang.Object ref = serverId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                serverId_ = s;
                return s;
            }
        }

        /**
         * <code>string server_id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getServerIdBytes() {
            java.lang.Object ref = serverId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                serverId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PEER_ID_FIELD_NUMBER = 2;
        private volatile java.lang.Object peerId_;

        /**
         * <code>string peer_id = 2;</code>
         */
        public java.lang.String getPeerId() {
            java.lang.Object ref = peerId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                peerId_ = s;
                return s;
            }
        }

        /**
         * <code>string peer_id = 2;</code>
         */
        public com.google.protobuf.ByteString
        getPeerIdBytes() {
            java.lang.Object ref = peerId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                peerId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TERM_FIELD_NUMBER = 3;
        private long term_;

        /**
         * <code>uint64 term = 3;</code>
         */
        public long getTerm() {
            return term_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getServerIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverId_);
            }
            if (!getPeerIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, peerId_);
            }
            if (term_ != 0L) {
                output.writeUInt64(3, term_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (!getServerIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverId_);
            }
            if (!getPeerIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, peerId_);
            }
            if (term_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, term_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq)) {
                return super.equals(obj);
            }
            io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq other = (io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq) obj;

            boolean result = true;
            result = result && getServerId()
                    .equals(other.getServerId());
            result = result && getPeerId()
                    .equals(other.getPeerId());
            result = result && (getTerm()
                    == other.getTerm());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
            hash = (53 * hash) + getServerId().hashCode();
            hash = (37 * hash) + PEER_ID_FIELD_NUMBER;
            hash = (53 * hash) + getPeerId().hashCode();
            hash = (37 * hash) + TERM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTerm());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.zealab.kvaft.rpc.protoc.PreVoteReq}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.zealab.kvaft.rpc.protoc.PreVoteReq)
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReqOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq.class, io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq.Builder.class);
            }

            // Construct using io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                serverId_ = "";

                peerId_ = "";

                term_ = 0L;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_descriptor;
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq getDefaultInstanceForType() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq.getDefaultInstance();
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq build() {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq buildPartial() {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq result = new io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq(this);
                result.serverId_ = serverId_;
                result.peerId_ = peerId_;
                result.term_ = term_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq) {
                    return mergeFrom((io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq other) {
                if (other == io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq.getDefaultInstance()) {
                    return this;
                }
                if (!other.getServerId().isEmpty()) {
                    serverId_ = other.serverId_;
                    onChanged();
                }
                if (!other.getPeerId().isEmpty()) {
                    peerId_ = other.peerId_;
                    onChanged();
                }
                if (other.getTerm() != 0L) {
                    setTerm(other.getTerm());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object serverId_ = "";

            /**
             * <code>string server_id = 1;</code>
             */
            public java.lang.String getServerId() {
                java.lang.Object ref = serverId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    serverId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string server_id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getServerIdBytes() {
                java.lang.Object ref = serverId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    serverId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string server_id = 1;</code>
             */
            public Builder setServerId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                serverId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string server_id = 1;</code>
             */
            public Builder clearServerId() {

                serverId_ = getDefaultInstance().getServerId();
                onChanged();
                return this;
            }

            /**
             * <code>string server_id = 1;</code>
             */
            public Builder setServerIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                serverId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object peerId_ = "";

            /**
             * <code>string peer_id = 2;</code>
             */
            public java.lang.String getPeerId() {
                java.lang.Object ref = peerId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    peerId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string peer_id = 2;</code>
             */
            public com.google.protobuf.ByteString
            getPeerIdBytes() {
                java.lang.Object ref = peerId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    peerId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string peer_id = 2;</code>
             */
            public Builder setPeerId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                peerId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string peer_id = 2;</code>
             */
            public Builder clearPeerId() {

                peerId_ = getDefaultInstance().getPeerId();
                onChanged();
                return this;
            }

            /**
             * <code>string peer_id = 2;</code>
             */
            public Builder setPeerIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                peerId_ = value;
                onChanged();
                return this;
            }

            private long term_;

            /**
             * <code>uint64 term = 3;</code>
             */
            public long getTerm() {
                return term_;
            }

            /**
             * <code>uint64 term = 3;</code>
             */
            public Builder setTerm(long value) {

                term_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 term = 3;</code>
             */
            public Builder clearTerm() {

                term_ = 0L;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:io.zealab.kvaft.rpc.protoc.PreVoteReq)
        }

        // @@protoc_insertion_point(class_scope:io.zealab.kvaft.rpc.protoc.PreVoteReq)
        private static final io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq();
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PreVoteReq>
                PARSER = new com.google.protobuf.AbstractParser<PreVoteReq>() {
            @java.lang.Override
            public PreVoteReq parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PreVoteReq(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<PreVoteReq> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PreVoteReq> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface PreVoteAckOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.zealab.kvaft.rpc.protoc.PreVoteAck)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 term = 1;</code>
         */
        long getTerm();

        /**
         * <code>bool authorized = 2;</code>
         */
        boolean getAuthorized();
    }

    /**
     * Protobuf type {@code io.zealab.kvaft.rpc.protoc.PreVoteAck}
     */
    public static final class PreVoteAck extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.zealab.kvaft.rpc.protoc.PreVoteAck)
            PreVoteAckOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use PreVoteAck.newBuilder() to construct.
        private PreVoteAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private PreVoteAck() {
            term_ = 0L;
            authorized_ = false;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private PreVoteAck(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            term_ = input.readUInt64();
                            break;
                        }
                        case 16: {

                            authorized_ = input.readBool();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck.class, io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck.Builder.class);
        }

        public static final int TERM_FIELD_NUMBER = 1;
        private long term_;

        /**
         * <code>uint64 term = 1;</code>
         */
        public long getTerm() {
            return term_;
        }

        public static final int AUTHORIZED_FIELD_NUMBER = 2;
        private boolean authorized_;

        /**
         * <code>bool authorized = 2;</code>
         */
        public boolean getAuthorized() {
            return authorized_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (term_ != 0L) {
                output.writeUInt64(1, term_);
            }
            if (authorized_ != false) {
                output.writeBool(2, authorized_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (term_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, term_);
            }
            if (authorized_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, authorized_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck)) {
                return super.equals(obj);
            }
            io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck other = (io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck) obj;

            boolean result = true;
            result = result && (getTerm()
                    == other.getTerm());
            result = result && (getAuthorized()
                    == other.getAuthorized());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TERM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTerm());
            hash = (37 * hash) + AUTHORIZED_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getAuthorized());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.zealab.kvaft.rpc.protoc.PreVoteAck}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.zealab.kvaft.rpc.protoc.PreVoteAck)
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAckOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck.class, io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck.Builder.class);
            }

            // Construct using io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                term_ = 0L;

                authorized_ = false;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_descriptor;
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck getDefaultInstanceForType() {
                return io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck.getDefaultInstance();
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck build() {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck buildPartial() {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck result = new io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck(this);
                result.term_ = term_;
                result.authorized_ = authorized_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck) {
                    return mergeFrom((io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck other) {
                if (other == io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck.getDefaultInstance()) {
                    return this;
                }
                if (other.getTerm() != 0L) {
                    setTerm(other.getTerm());
                }
                if (other.getAuthorized() != false) {
                    setAuthorized(other.getAuthorized());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long term_;

            /**
             * <code>uint64 term = 1;</code>
             */
            public long getTerm() {
                return term_;
            }

            /**
             * <code>uint64 term = 1;</code>
             */
            public Builder setTerm(long value) {

                term_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 term = 1;</code>
             */
            public Builder clearTerm() {

                term_ = 0L;
                onChanged();
                return this;
            }

            private boolean authorized_;

            /**
             * <code>bool authorized = 2;</code>
             */
            public boolean getAuthorized() {
                return authorized_;
            }

            /**
             * <code>bool authorized = 2;</code>
             */
            public Builder setAuthorized(boolean value) {

                authorized_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool authorized = 2;</code>
             */
            public Builder clearAuthorized() {

                authorized_ = false;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:io.zealab.kvaft.rpc.protoc.PreVoteAck)
        }

        // @@protoc_insertion_point(class_scope:io.zealab.kvaft.rpc.protoc.PreVoteAck)
        private static final io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck();
        }

        public static io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PreVoteAck>
                PARSER = new com.google.protobuf.AbstractParser<PreVoteAck>() {
            @java.lang.Override
            public PreVoteAck parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PreVoteAck(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<PreVoteAck> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PreVoteAck> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public io.zealab.kvaft.rpc.protoc.RemoteCalls.PreVoteAck getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017kvaft-rpc.proto\022\032io.zealab.kvaft.rpc.p" +
                        "rotoc\"\036\n\tHeartbeat\022\021\n\ttimestamp\030\001 \001(\003\">\n" +
                        "\nPreVoteReq\022\021\n\tserver_id\030\001 \001(\t\022\017\n\007peer_i" +
                        "d\030\002 \001(\t\022\014\n\004term\030\003 \001(\004\".\n\nPreVoteAck\022\014\n\004t" +
                        "erm\030\001 \001(\004\022\022\n\nauthorized\030\002 \001(\010B)\n\032io.zeal" +
                        "ab.kvaft.rpc.protocB\013RemoteCallsb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_zealab_kvaft_rpc_protoc_Heartbeat_descriptor,
                new java.lang.String[]{"Timestamp",});
        internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_zealab_kvaft_rpc_protoc_PreVoteReq_descriptor,
                new java.lang.String[]{"ServerId", "PeerId", "Term",});
        internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_zealab_kvaft_rpc_protoc_PreVoteAck_descriptor,
                new java.lang.String[]{"Term", "Authorized",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
